struct VIn
{
    float4 p    : POSITION;
    float2 uv   : TEXCOORD0;
};
 
void endlessLine_vs(VIn IN,
    uniform float4x4 wvpMat,
    out float4 oPos : POSITION,
    out float2 oUV : TEXCOORD0)
{
    oPos = mul(wvpMat, IN.p);
    oUV = IN.uv;
}
 
float4 endlessLine_ps(in float2 uv : TEXCOORD0,
    uniform float4 color : COLOR0,
    uniform sampler2D diffuseMap): COLOR0
{    
    return tex2D(diffuseMap, float2(uv.x + color.a, uv.y)) * float4(color.rgb, 1.0);
}